# global config
:global:
  :log:
    # log levels: DEBUG	=	0, INFO	=	1, WARN	=	2, ERROR	=	3, FATAL	=	4,UNKNOWN	=	5
    :level: 0
    :filename: monitor.log
  :classes:
    - ping
    - cpu

# env specific config
:development:
  :ping:
    :host:
      - "google.com"
      - "google.rs"
      - "123skins.de"
    :timeout: 10
    :port: 80
  :cpu:
    :limit:
      :one_min: 10
      :five_min: 10
      :fifteen_min: 10